# Generated by Django 3.2.4 on 2021-06-08 12:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Tên')),
                ('TacGia', models.CharField(max_length=40, verbose_name='Tác giả')),
                ('Upload', models.FileField(upload_to='Book')),
                ('TheLoai', models.CharField(choices=[('LichSu', 'Lịch sử'), ('NghiLe', 'Nghi lễ'), ('PhatHoc', 'Phật học')], max_length=30, verbose_name='Thể Loại')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='InfoCauNguyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='CauNguyen', verbose_name='Hình Ảnh')),
                ('LoiCauNguyen', models.TextField(verbose_name='Lời Cầu Nguyện')),
                ('ThoiGianCauNguyen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời Gian')),
            ],
        ),
        migrations.CreateModel(
            name='QuaLuuNiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='Tên')),
                ('Image', models.ImageField(upload_to='Qua', verbose_name='Hình Ảnh')),
                ('Price', models.IntegerField(null=True, verbose_name='Giá')),
                ('Description', models.TextField(default='Chưa có mô tả', max_length=10000, verbose_name='Mô tả')),
            ],
            options={
                'ordering': ('Name', 'Price'),
            },
        ),
        migrations.CreateModel(
            name='VanHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Tên')),
                ('TacGia', models.CharField(max_length=40, null=True, verbose_name='Tác giả')),
                ('Upload', models.FileField(upload_to='VanHoa')),
                ('TheLoai', models.CharField(choices=[('SongDep', 'Sống đẹp'), ('NauChay', 'Nấu chay'), ('AnChay', 'Ăn chay')], max_length=30, verbose_name='Thể Loại')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='InfoCauAn',
            fields=[
                ('infocaunguyen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ViengChua.infocaunguyen')),
                ('HoTen', models.CharField(max_length=50, verbose_name='Họ và Tên')),
                ('NgaySinh', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày Sinh')),
                ('PhapDanh', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pháp Danh')),
                ('GioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3, verbose_name='Giới Tính')),
                ('DiaChi', models.CharField(max_length=60, verbose_name='Địa Chỉ')),
                ('QueQuan', models.CharField(max_length=60, verbose_name='Quê Quán')),
            ],
            options={
                'ordering': ('-ThoiGianCauNguyen',),
            },
            bases=('ViengChua.infocaunguyen', models.Model),
        ),
        migrations.CreateModel(
            name='InfoCauSieu',
            fields=[
                ('infocaunguyen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ViengChua.infocaunguyen')),
                ('HoTen', models.CharField(max_length=50, verbose_name='Họ và Tên')),
                ('NgaySinh', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày Sinh')),
                ('PhapDanh', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pháp Danh')),
                ('GioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3, verbose_name='Giới Tính')),
                ('DiaChi', models.CharField(max_length=60, verbose_name='Địa Chỉ')),
                ('QueQuan', models.CharField(max_length=60, verbose_name='Quê Quán')),
                ('NgayMat', models.DateField(verbose_name='Ngày Mất')),
                ('HuongDuong', models.PositiveIntegerField(verbose_name='Hưởng Dương')),
            ],
            options={
                'ordering': ('-ThoiGianCauNguyen',),
            },
            bases=('ViengChua.infocaunguyen', models.Model),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('HoTen', models.CharField(max_length=50, verbose_name='Họ và Tên')),
                ('NgaySinh', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày Sinh')),
                ('PhapDanh', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pháp Danh')),
                ('GioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3, verbose_name='Giới Tính')),
                ('DiaChi', models.CharField(max_length=60, verbose_name='Địa Chỉ')),
                ('QueQuan', models.CharField(max_length=60, verbose_name='Quê Quán')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('date_joined', 'username'),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InfoLienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Comment', models.TextField(verbose_name='Comment')),
                ('Time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('CommentUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Name', 'Email', 'Time'),
            },
        ),
        migrations.AddField(
            model_name='infocaunguyen',
            name='CommentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
